### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1415: character maps to <undefined>

### ISSUE THREAD

**Issue by maglionejm** [MrXandbadas/openAI_Assistant_API_DEMO#2]
**Full error:** 

```
Traceback (most recent call last):
  File "C:\Users\maglione juan martin\openAI_Assistant_API_DEMO-main\customer_inquiry_assistant.py", line 2, in <module>
    from agent_class import OAI_Agent
  File "C:\Users\maglione juan martin\openAI_Assistant_API_DEMO-main\agent_class.py", line 4, in <module>
    import gpt3_tokenizer
  File "C:\Users\maglione juan martin\openAI_Assistant_API_DEMO-main\venv\Lib\site-packages\gpt3_tokenizer\__init__.py", line 1, in <module>
    from gpt3_tokenizer._entry import count_tokens, decode, encode
  File "C:\Users\maglione juan martin\openAI_Assistant_API_DEMO-main\venv\Lib\site-packages\gpt3_tokenizer\_entry.py", line 10, in <module>
    _bpe_merges = _get_bpe_merges()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\maglione juan martin\openAI_Assistant_API_DEMO-main\venv\Lib\site-packages\gpt3_tokenizer\_functions.py", line 20, in _get_bpe_merges
    bpe_lines = f.readlines()
                ^^^^^^^^^^^^^
  File "C:\Users\maglione juan martin\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1415: character maps to <undefined>
```

I'm receiving this error although there are no instances of file reading operations (like open() in read mode) in the Python files from your uploaded zip file (agent_class.py and customer_inquiry_assistant.py). This means the UnicodeDecodeError you are experiencing is not due to these files directly.

Why do you think this is happening?

**Comment by maglionejm** [comment]
Here are the changes to the two functions where file reading occurs, _init_encoder and _get_bpe_merges, to explicitly specify the UTF-8 encoding:

`def _init_encoder():
    with open(os.path.join(os.path.dirname(__file__), 'data/encoder.json'), 'r', encoding='utf-8') as f:
        encoder = json.load(f)
        return encoder

def _get_bpe_merges():
    with open(os.path.join(os.path.dirname(__file__), "data/vocab.bpe"), "r", encoding='utf-8') as f:
        bpe_lines = f.readlines()    
        sliced = bpe_lines[1:len(bpe_lines)-1]
        bpe_merges = [regex.split(r"(\s+)", s) for s in sliced]
        final_merges = []
        for merge in bpe_merges:
            final_merges.append([m for m in merge if len(m.strip()) > 0])
        return final_merges
`
